version: '3.8'
services:
  db: 
    container_name: mongo_db
    image: mongo
    network_mode: "host"
    environment:
      - MONGO_INITDB_DATABASE=graphql
      
  app:
    container_name: app_graphQl
    build: .
    volumes:
      - '.:/usr/app'
    network_mode: "host"